# The purpose of this -test example is for the e2e tests of this project
#
# Usage:
#  docker-compose -p grid up --force-recreate
#  docker-compose -p grid scale mock=1 hub=1 chrome=3 firefox=3
version: '3.7'

services:
  hub:
    image: elgalu/selenium:3.14.0-p9
    ports:
      # Note 24444 is the default SELENIUM_HUB_PORT inside the container
      #  and  4444 will be mapped into your host for easy access.
      - 4444:4444
      # We need a fixed port range to expose VNC
      # due to a bug in Docker for Mac beta (1.12)
      # https://forums.docker.com/t/docker-for-mac-beta-not-forwarding-ports/8658/6
      - ${VNC_FROM_PORT-40650}-${VNC_TO_PORT-40700}:${VNC_FROM_PORT-40650}-${VNC_TO_PORT-40700}
      # e.g. (hard-coded)
      # - 40650-40700:40650-40700
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - DEBUG=false
      - PICK_ALL_RANDOM_PORTS=true
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - GRID=true
      - CHROME=false
      - FIREFOX=false
      - MOCK_SERVER_HOST=mock
      - GRID_TIMEOUT=720
      - GRID_BROWSER_TIMEOUT=360
      - COMPOSE_HTTP_TIMEOUT=120
      - DOCKER_CLIENT_TIMEOUT=120
      - TZ=Europe/Istanbul
      - LANGUAGE=en_US:en
      - LANG=en_US.UTF-8

  chromenode:
    image: elgalu/selenium:3.14.0-p9
    depends_on:
      - hub
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - DEBUG=false
      - PICK_ALL_RANDOM_PORTS=true
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - SELENIUM_NODE_HOST={{CONTAINER_IP}}
      - VNC_FROM_PORT=${VNC_FROM_PORT-40650}
      - VNC_TO_PORT=${VNC_TO_PORT-40700}
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - VIDEO=${VIDEO-false}
      - GRID=false
      - CHROME=true
      - FIREFOX=false
      - HUB_HOST=hub
      - HUB_PORT=4444
      - TZ=Europe/Istanbul
      - LANGUAGE=en_US:en
      - LANG=en_US.UTF-8

  firefox:
    image: elgalu/selenium:3.14.0-p9
    depends_on:
      - hub
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - DEBUG=false
      - PICK_ALL_RANDOM_PORTS=true
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - SELENIUM_NODE_HOST={{CONTAINER_IP}}
      - VNC_FROM_PORT=${VNC_FROM_PORT-40650}
      - VNC_TO_PORT=${VNC_TO_PORT-40700}
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - VIDEO=${VIDEO-false}
      - GRID=false
      - CHROME=false
      - FIREFOX=true
      - HUB_HOST=hub
      - HUB_PORT=4444
      - TZ=Europe/Istanbul
      - LANGUAGE=en_US:en
      - LANG=en_US.UTF-8
